
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class AddressesSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddressesSubmenuGUI.class.getName());
    private Customer customer;
    private AddressManager am;
    private DefaultListModel model;
    /**
     * Creates new form AddressesSubmenuGUI
     */
    public AddressesSubmenuGUI() {
        model = new DefaultListModel();
        initComponents();
        updateAddrButton.setEnabled(false);
        removeAddrButton.setEnabled(false);
    }
    
    public AddressesSubmenuGUI(Customer customer) {
        this();
        this.customer = customer;
        am = customer.getAddressManager();
        initializeAddresses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageAddrDescrLabel = new javax.swing.JLabel();
        addrOnFilePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressList = new javax.swing.JList<>();
        addAddrButton = new javax.swing.JButton();
        updateAddrButton = new javax.swing.JButton();
        removeAddrButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        manageAddrDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        manageAddrDescrLabel.setText("Manage Addresses");

        addrOnFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Addresses on File"));

        addressList.setModel(model);
        addressList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                addressListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(addressList);

        addAddrButton.setText("Add New Address");
        addAddrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddrButtonActionPerformed(evt);
            }
        });

        updateAddrButton.setText("Update Address");
        updateAddrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAddrButtonActionPerformed(evt);
            }
        });

        removeAddrButton.setText("Remove Address");
        removeAddrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAddrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addrOnFilePanelLayout = new javax.swing.GroupLayout(addrOnFilePanel);
        addrOnFilePanel.setLayout(addrOnFilePanelLayout);
        addrOnFilePanelLayout.setHorizontalGroup(
            addrOnFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addrOnFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addrOnFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(addrOnFilePanelLayout.createSequentialGroup()
                        .addComponent(addAddrButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateAddrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeAddrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addrOnFilePanelLayout.setVerticalGroup(
            addrOnFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addrOnFilePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addrOnFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAddrButton)
                    .addComponent(updateAddrButton)
                    .addComponent(removeAddrButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageAddrDescrLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addrOnFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageAddrDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrOnFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addressListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_addressListValueChanged
        // TODO add your handling code here:
        
        updateAddrButton.setEnabled(true);
        removeAddrButton.setEnabled(true);
    }//GEN-LAST:event_addressListValueChanged

    private void removeAddrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAddrButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this address?", "Remove Address", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            int id = addressList.getSelectedIndex();
            model.removeElementAt(id);
            am.deleteAddress(id + 1);
        }
    }//GEN-LAST:event_removeAddrButtonActionPerformed

    private void updateAddrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAddrButtonActionPerformed
        // TODO add your handling code here:
        
        Address address = am.searchAddress(addressList.getSelectedIndex() + 1);
        
        EditAddressSubmenuGUI easGUI = new EditAddressSubmenuGUI(address, am, true);
        easGUI.setVisible(true);
        
    }//GEN-LAST:event_updateAddrButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
        refreshAddresses();
    }//GEN-LAST:event_formWindowGainedFocus

    private void addAddrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddrButtonActionPerformed
        // TODO add your handling code here:
        
        IDGenerator idGenerator = new IDGenerator();
        
        int id;
        
        id = idGenerator.generateId(am);
        
        Address address = new Address(customer, id);
        model.addElement("");
        EditAddressSubmenuGUI easGUI = new EditAddressSubmenuGUI(address, am, false);
        easGUI.setVisible(true);
    }//GEN-LAST:event_addAddrButtonActionPerformed
    
    private void initializeAddresses(){
        int numAddresses = am.getNumAddresses();
        
        for(int i = 1; i <= numAddresses; i++){
            Address addr = am.searchAddress(i);
            
            if(addr != null){
                String addrInfo = addr.stringAddressInformation();
                model.addElement(addrInfo);
            }
        }
    }
    
    private void refreshAddresses(){
        
        int numAddresses = am.getNumAddresses();
        
        for(int i = 1; i <= numAddresses; i++){
            Address addr = am.searchAddress(i);
            
            if(addr != null){
                String addrInfo = addr.stringAddressInformation();
                model.set(i - 1, addrInfo);
            }
        }
        
        addressList.updateUI();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddressesSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAddrButton;
    private javax.swing.JPanel addrOnFilePanel;
    private javax.swing.JList<String> addressList;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageAddrDescrLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeAddrButton;
    private javax.swing.JButton updateAddrButton;
    // End of variables declaration//GEN-END:variables
}
