
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class CustomerMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerMenuGUI.class.getName());
    private CustomerSettingsSubmenu css;
    private CustomerSubmenuManager csubm;
    private CustomerManager cm;
    private Customer customer;
    private OrderManager gom;
    private Menu menu;
    private Inventory inventory;
    private int customerId;
    private DefaultListModel unfulfilledOrdersModel;
    private Map<Integer, Order> unfulfilledOrders;
    private PlaceOrderMenuGUI pomGUI;

    /**
     * Creates new form CustomerMenuGUI
     */
    public CustomerMenuGUI() {
        unfulfilledOrdersModel = new DefaultListModel();
        initComponents();
        viewOrderInfoBttn.setEnabled(false);
    }
    
    public CustomerMenuGUI(CustomerManager cm, int id, OrderManager gom, Menu menu, 
            Restaurant restaurant, Inventory inventory, CostCalculation cc){
        this();
        this.cm = cm;
        customerId = id;
        customer = this.cm.searchCustomer(customerId);
        this.gom = gom;
        this.menu = menu;
        this.inventory = inventory;

        refreshInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        whatDoLabel = new javax.swing.JLabel();
        placeOrderBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inProgOrdersLst = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        viewOrderInfoBttn = new javax.swing.JButton();
        customerMenuMenuBar = new javax.swing.JMenuBar();
        customerSubmenu = new javax.swing.JMenu();
        profileMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        OrdersSubmenu = new javax.swing.JMenu();
        orderHistMenuItem = new javax.swing.JMenuItem();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Menu");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        welcomeLabel.setText("Welcome, Customer!");

        whatDoLabel.setText("What would you like to do today?");

        placeOrderBttn.setText("Place an Order");
        placeOrderBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBttnActionPerformed(evt);
            }
        });

        inProgOrdersLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        inProgOrdersLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                inProgOrdersLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(inProgOrdersLst);

        jLabel3.setText("Orders in Progress");

        viewOrderInfoBttn.setText("View Order Information");
        viewOrderInfoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderInfoBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(viewOrderInfoBttn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(whatDoLabel)
                            .addComponent(placeOrderBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whatDoLabel)
                .addGap(5, 5, 5)
                .addComponent(placeOrderBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewOrderInfoBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerSubmenu.setText("Customer");

        profileMenuItem.setText("Profile Settings");
        profileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuItemActionPerformed(evt);
            }
        });
        customerSubmenu.add(profileMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        customerSubmenu.add(logoutMenuItem);

        customerMenuMenuBar.add(customerSubmenu);

        OrdersSubmenu.setText("Orders");

        orderHistMenuItem.setText("Order History");
        orderHistMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistMenuItemActionPerformed(evt);
            }
        });
        OrdersSubmenu.add(orderHistMenuItem);

        customerMenuMenuBar.add(OrdersSubmenu);

        setJMenuBar(customerMenuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBttnActionPerformed
        // TODO add your handling code here:
        new PlaceOrderMenuGUI(customer, gom, menu, inventory).setVisible(true);
    }//GEN-LAST:event_placeOrderBttnActionPerformed

    private void profileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuItemActionPerformed
        // TODO add your handling code here:
        if(!customer.isGuest()){
            CustomerSettingsSubmenuGUI cssGUI = new CustomerSettingsSubmenuGUI(cm, customerId);
            cssGUI.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "This option is reserved for customers with a user profile.");
        }
    }//GEN-LAST:event_profileMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Log out", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        refreshInfo();
    }//GEN-LAST:event_formWindowGainedFocus

    private void viewOrderInfoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderInfoBttnActionPerformed
        // TODO add your handling code here:

        String selectedOrder = inProgOrdersLst.getSelectedValue();
        int id = retrieveOrderID(selectedOrder);
        Order order = unfulfilledOrders.get(id);
        new ViewOrderInfoGUI(order).setVisible(true);
    }//GEN-LAST:event_viewOrderInfoBttnActionPerformed

    private void inProgOrdersLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_inProgOrdersLstValueChanged
        // TODO add your handling code here:
        viewOrderInfoBttn.setEnabled(inProgOrdersLst.getSelectedIndex() > -1);
    }//GEN-LAST:event_inProgOrdersLstValueChanged

    private void orderHistMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistMenuItemActionPerformed
        // TODO add your handling code here:
        new OrderHistoryGUI(customer).setVisible(true);
    }//GEN-LAST:event_orderHistMenuItemActionPerformed
    
    private void refreshInfo(){
        welcomeLabel.setText("Welcome, " + customer.getName() + "!");
        showUnfulfilledOrders();
    }
    
    private void showUnfulfilledOrders(){
        unfulfilledOrders = customer.getOrderHistory().getUnfulfilledOrders();
        
        
        unfulfilledOrdersModel = new DefaultListModel();
        
        if(!unfulfilledOrders.isEmpty()){
            for(int id: unfulfilledOrders.keySet()){
                Order order =  unfulfilledOrders.get(id);
                unfulfilledOrdersModel.addElement("Order #" + order.getOrderId());
            }
        }
        inProgOrdersLst.setModel(unfulfilledOrdersModel);
        inProgOrdersLst.updateUI();
    }
    
    private int retrieveOrderID(String str){
        String orderIDStr = str.replace("Order #", "");
        int id = Integer.parseInt(orderIDStr);
        return id;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu OrdersSubmenu;
    private javax.swing.JMenuBar customerMenuMenuBar;
    private javax.swing.JMenu customerSubmenu;
    private javax.swing.JList<String> inProgOrdersLst;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem orderHistMenuItem;
    private javax.swing.JButton placeOrderBttn;
    private javax.swing.JMenuItem profileMenuItem;
    private javax.swing.JButton viewOrderInfoBttn;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel whatDoLabel;
    // End of variables declaration//GEN-END:variables
}
