/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class CustomerSettingsSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerSettingsSubmenuGUI.class.getName());
    
    private CustomerSettingsManager csm;
    private CustomerManager cm;
    private Customer customer;
    private AddressesSubmenu as;
    private PhoneSubmenu ps;
    private int customerId;
    
    /**
     * Creates new form CustomerSettingsSubmenuGUI
     */
    public CustomerSettingsSubmenuGUI() {
        initComponents();
    }
    
    public CustomerSettingsSubmenuGUI(CustomerManager cm, int id){
        this();
        this.cm = cm;
        customerId = id;
        customer = cm.searchCustomer(id);
        csm = new CustomerSettingsManager(this.cm);
        as = new AddressesSubmenu(customer);
        ps = new PhoneSubmenu(customer);
        
        refreshInformation();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInfoPanel = new javax.swing.JPanel();
        customerInfoLabel = new javax.swing.JLabel();
        editInfoButton = new javax.swing.JButton();
        settingsDescrLabel = new javax.swing.JLabel();
        contactInfoPanel = new javax.swing.JPanel();
        primaryAddressPanel = new javax.swing.JPanel();
        primaryAddressLabel = new javax.swing.JLabel();
        manageAddressButton = new javax.swing.JButton();
        phoneNumberPanel = new javax.swing.JPanel();
        managePhoneButton = new javax.swing.JButton();
        payInfoPanel = new javax.swing.JPanel();
        payMethodLabel = new javax.swing.JLabel();
        managePaymentButton = new javax.swing.JButton();
        exitSaveButton = new javax.swing.JButton();
        exitWOSaveButton = new javax.swing.JButton();
        revertButton = new javax.swing.JButton();
        deleteAcctDescrLabel = new javax.swing.JLabel();
        deleteAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        customerInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));
        customerInfoPanel.setToolTipText("Customer Information");

        customerInfoLabel.setText("<html>Customer name: name<br>Customer ID: 000<br>Email Address: emailaddress12345@email.com<br>");

        editInfoButton.setText("Edit Information");
        editInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInfoPanelLayout = new javax.swing.GroupLayout(customerInfoPanel);
        customerInfoPanel.setLayout(customerInfoPanelLayout);
        customerInfoPanelLayout.setHorizontalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editInfoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerInfoPanelLayout.setVerticalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addComponent(customerInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editInfoButton)
                .addContainerGap())
        );

        settingsDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        settingsDescrLabel.setText("Profile Settings");

        contactInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Information"));

        primaryAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Primary Address"));

        primaryAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        primaryAddressLabel.setText("<html>address line 1<br>address line 2<br>city, state, 00000");

        manageAddressButton.setText("Manage Addresses");
        manageAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAddressButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout primaryAddressPanelLayout = new javax.swing.GroupLayout(primaryAddressPanel);
        primaryAddressPanel.setLayout(primaryAddressPanelLayout);
        primaryAddressPanelLayout.setHorizontalGroup(
            primaryAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primaryAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAddressButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        primaryAddressPanelLayout.setVerticalGroup(
            primaryAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryAddressPanelLayout.createSequentialGroup()
                .addComponent(primaryAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAddressButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        phoneNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Numbers"));

        managePhoneButton.setText("Manage Phone Numbers");

        javax.swing.GroupLayout phoneNumberPanelLayout = new javax.swing.GroupLayout(phoneNumberPanel);
        phoneNumberPanel.setLayout(phoneNumberPanelLayout);
        phoneNumberPanelLayout.setHorizontalGroup(
            phoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managePhoneButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phoneNumberPanelLayout.setVerticalGroup(
            phoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(managePhoneButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout contactInfoPanelLayout = new javax.swing.GroupLayout(contactInfoPanel);
        contactInfoPanel.setLayout(contactInfoPanelLayout);
        contactInfoPanelLayout.setHorizontalGroup(
            contactInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primaryAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contactInfoPanelLayout.setVerticalGroup(
            contactInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoPanelLayout.createSequentialGroup()
                .addComponent(primaryAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        payInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Information"));

        payMethodLabel.setText("Current Pay Method: pay method");

        managePaymentButton.setText("Manage Payment Information");

        javax.swing.GroupLayout payInfoPanelLayout = new javax.swing.GroupLayout(payInfoPanel);
        payInfoPanel.setLayout(payInfoPanelLayout);
        payInfoPanelLayout.setHorizontalGroup(
            payInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payMethodLabel)
                    .addComponent(managePaymentButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        payInfoPanelLayout.setVerticalGroup(
            payInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payMethodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(managePaymentButton)
                .addContainerGap())
        );

        exitSaveButton.setText("Exit and Save");

        exitWOSaveButton.setText("Exit Without Saving");

        revertButton.setText("Revert Information");

        deleteAcctDescrLabel.setText("If you want to delete your account,");

        deleteAccountLabel.setForeground(new java.awt.Color(255, 0, 0));
        deleteAccountLabel.setText("click here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsDescrLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(deleteAcctDescrLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteAccountLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(exitSaveButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exitWOSaveButton)))
                                .addGap(10, 10, 10)
                                .addComponent(revertButton)))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitSaveButton)
                    .addComponent(exitWOSaveButton)
                    .addComponent(revertButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAcctDescrLabel)
                    .addComponent(deleteAccountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(514, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAddressButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageAddressButtonActionPerformed

    private void editInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButtonActionPerformed
        // TODO add your handling code here:
        UserInfoGUI uiGUI = new UserInfoGUI(customer);
        uiGUI.setVisible(true);
    }//GEN-LAST:event_editInfoButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        refreshInformation();
    }//GEN-LAST:event_formWindowGainedFocus
    
    private void refreshInformation(){
        displayCustomerInfo();
        displayAddress();
        displayPayMethod();
    }
    
    private void displayCustomerInfo(){
        customerInfoLabel.setText(customer.toString());
    }
    
    private void displayAddress(){
        int id = customer.getAddressManager().getPrimaryAddressID();
        Address addr = customer.getAddressManager().searchAddress(id);
        if(addr != null)
            primaryAddressLabel.setText(addr.toString());
        else
            primaryAddressLabel.setText("Primary Address has not been set.");
    }
    
    private void displayPayMethod(){
        String payMethod = customer.getPayment().getCurrentPayMethod();
        if(!payMethod.isEmpty())
            payMethodLabel.setText("Current Pay Method: " + payMethod);
        else
            payMethodLabel.setText("Current Pay Method: none");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerSettingsSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contactInfoPanel;
    private javax.swing.JLabel customerInfoLabel;
    private javax.swing.JPanel customerInfoPanel;
    private javax.swing.JLabel deleteAccountLabel;
    private javax.swing.JLabel deleteAcctDescrLabel;
    private javax.swing.JButton editInfoButton;
    private javax.swing.JButton exitSaveButton;
    private javax.swing.JButton exitWOSaveButton;
    private javax.swing.JButton manageAddressButton;
    private javax.swing.JButton managePaymentButton;
    private javax.swing.JButton managePhoneButton;
    private javax.swing.JPanel payInfoPanel;
    private javax.swing.JLabel payMethodLabel;
    private javax.swing.JPanel phoneNumberPanel;
    private javax.swing.JLabel primaryAddressLabel;
    private javax.swing.JPanel primaryAddressPanel;
    private javax.swing.JButton revertButton;
    private javax.swing.JLabel settingsDescrLabel;
    // End of variables declaration//GEN-END:variables
}
