
import javax.swing.JOptionPane;

/**
 * This class provides a GUI menu for an employee user to edit the information 
 * about their delivery vehicle that they have stored on their profile.
 * @author Alexander
 */
public class EditVehicleSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditAddressSubmenuGUI.class.getName());
    private Vehicle vehicle;
    
    /**
     * Creates new form EditAddressSubmenuGUI
     */
    public EditVehicleSubmenuGUI() {
        initComponents();
    }
    
    public EditVehicleSubmenuGUI(Vehicle vehicle) {
        this();
        this.vehicle = vehicle;
        if(vehicle != null){setFields();}
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editVhclDescrLabel = new javax.swing.JLabel();
        vhclPanel = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        licensePlateLabel = new javax.swing.JLabel();
        modelTF = new javax.swing.JTextField();
        makeTF = new javax.swing.JTextField();
        colorTF = new javax.swing.JTextField();
        licensePlateTF = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        yearCBox = new javax.swing.JComboBox<>();
        bodyStyleTF = new javax.swing.JTextField();
        bodyStyleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editVhclDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        editVhclDescrLabel.setText("Edit Vehicle");

        vhclPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delivery Vehicle"));

        yearLabel.setText("Year");

        modelLabel.setText("Model");

        makeLabel.setText("Make");

        colorLabel.setText("Color");

        licensePlateLabel.setText("License Plate");

        modelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTFActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        yearCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900", "1899", "1898", "1897", "1896" }));

        bodyStyleLabel.setText("Body Style");

        javax.swing.GroupLayout vhclPanelLayout = new javax.swing.GroupLayout(vhclPanel);
        vhclPanel.setLayout(vhclPanelLayout);
        vhclPanelLayout.setHorizontalGroup(
            vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vhclPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vhclPanelLayout.createSequentialGroup()
                        .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel)
                            .addGroup(vhclPanelLayout.createSequentialGroup()
                                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(makeLabel)
                                    .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vhclPanelLayout.createSequentialGroup()
                                .addComponent(bodyStyleLabel)
                                .addGap(89, 89, 89)
                                .addComponent(colorLabel)
                                .addGap(115, 115, 115)
                                .addComponent(licensePlateLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vhclPanelLayout.createSequentialGroup()
                        .addComponent(bodyStyleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licensePlateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(vhclPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        vhclPanelLayout.setVerticalGroup(
            vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vhclPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(makeLabel))
                .addGap(1, 1, 1)
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelLabel)
                .addGap(3, 3, 3)
                .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyStyleLabel)
                    .addComponent(licensePlateLabel)
                    .addComponent(colorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyStyleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licensePlateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vhclPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editVhclDescrLabel)
                    .addComponent(vhclPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editVhclDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vhclPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if(hasChanged()){
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to apply these changes?", "Apply Changes", JOptionPane.YES_NO_OPTION);
        
            if(result == JOptionPane.YES_OPTION){
                setVehicle();
                this.dispose();
            }
        }
        else{
            this.dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(hasChanged()){
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel?", "Cancel", JOptionPane.YES_NO_OPTION);
        
            if(result == JOptionPane.YES_OPTION){
                this.dispose();
            }
        }
        else{
            this.dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void modelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTFActionPerformed
    
    private void setFields(){
        yearCBox.setSelectedItem(String.valueOf(vehicle.getYear()));
        makeTF.setText(vehicle.getMake());
        modelTF.setText(vehicle.getModel());
        bodyStyleTF.setText(vehicle.getBodyStyle());
        colorTF.setText(vehicle.getColor());
        licensePlateTF.setText(vehicle.getLicensePlate());
    }
    
    private void setVehicle(){
        vehicle.setYear(Short.parseShort((String) yearCBox.getSelectedItem()));
        vehicle.setMake(makeTF.getText());
        vehicle.setModel(modelTF.getText());
        vehicle.setBodyStyle(bodyStyleTF.getText());
        vehicle.setColor(colorTF.getText());
        vehicle.setLicensePlate(licensePlateTF.getText());
    }
    
    private boolean hasChanged(){
        if(vehicle != null){
            return !(vehicle.getYear() == (Short.parseShort((String) yearCBox.getSelectedItem())) &&
                    vehicle.getMake().equals(makeTF.getText()) &&
                    vehicle.getModel().equals(modelTF.getText()) &&
                    vehicle.getBodyStyle().equals(bodyStyleTF.getText()) &&
                    vehicle.getColor().equals(colorTF.getText()) &&
                    vehicle.getLicensePlate().equals(licensePlateTF.getText()));
        }
        else
            return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditAddressSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodyStyleLabel;
    private javax.swing.JTextField bodyStyleTF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTF;
    private javax.swing.JLabel editVhclDescrLabel;
    private javax.swing.JLabel licensePlateLabel;
    private javax.swing.JTextField licensePlateTF;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField makeTF;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTF;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel vhclPanel;
    private javax.swing.JComboBox<String> yearCBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
