/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class EditAddressSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditAddressSubmenuGUI.class.getName());
    private Address address;
    private AddressManager am;
    private boolean edit;
    
    /**
     * Creates new form EditAddressSubmenuGUI
     */
    public EditAddressSubmenuGUI() {
        initComponents();
    }
    
    public EditAddressSubmenuGUI(Address address, AddressManager am, boolean edit) {
        this();
        this.address = address;
        this.am = am;
        this.edit = edit;
        if(edit){
            editAddrDescrLabel.setText("Edit Address");
            setFields();
        }
        else{editAddrDescrLabel.setText("Create new Address");}
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editAddrDescrLabel = new javax.swing.JLabel();
        addrPanel = new javax.swing.JPanel();
        line1Label = new javax.swing.JLabel();
        line2Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        line1TF = new javax.swing.JTextField();
        line2TF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        stateTF = new javax.swing.JTextField();
        zipCodeTF = new javax.swing.JTextField();
        primaryChkBx = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editAddrDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        editAddrDescrLabel.setText("Edit Address");

        addrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        line1Label.setText("Line 1");

        line2Label.setText("Line 2 (Optional)");

        cityLabel.setText("City");

        stateLabel.setText("State");

        zipCodeLabel.setText("Zip Code");

        primaryChkBx.setText("Primary Address");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addrPanelLayout = new javax.swing.GroupLayout(addrPanel);
        addrPanel.setLayout(addrPanelLayout);
        addrPanelLayout.setHorizontalGroup(
            addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line2TF)
                    .addComponent(line1TF)
                    .addGroup(addrPanelLayout.createSequentialGroup()
                        .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line1Label)
                            .addComponent(line2Label)
                            .addComponent(primaryChkBx))
                        .addGap(252, 252, 252))
                    .addGroup(addrPanelLayout.createSequentialGroup()
                        .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLabel)
                            .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addrPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addrPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addrPanelLayout.createSequentialGroup()
                                .addComponent(zipCodeLabel)
                                .addGap(32, 32, 32))
                            .addComponent(zipCodeTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addrPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        addrPanelLayout.setVerticalGroup(
            addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line1Label)
                .addGap(1, 1, 1)
                .addComponent(line1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line2Label)
                .addGap(3, 3, 3)
                .addComponent(line2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(stateLabel)
                    .addComponent(zipCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primaryChkBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editAddrDescrLabel)
                    .addComponent(addrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editAddrDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        inputAddress();
        if(!edit){addAddress();}
        setPrimary();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setFields(){
        line1TF.setText(address.getLine1());
        line2TF.setText(address.getLine2());
        cityTF.setText(address.getCity());
        stateTF.setText(address.getState());
        zipCodeTF.setText(address.getZipCode());
        
        primaryChkBx.setSelected(address.isPrimary());
    }
    
    private void inputAddress(){
        address.setLine1(line1TF.getText());
        
        if(line2TF.getText().isEmpty()){address.setLine2("");}
        else{address.setLine2(line2TF.getText());}
        
        address.setCity(cityTF.getText());
        address.setState(stateTF.getText());
        address.setZipCode(zipCodeTF.getText());  
    }
    
    private void addAddress(){
        am.addAddress(address);
    }
    
    private void setPrimary(){
        if(primaryChkBx.isSelected()){
            am.setPrimaryAddress(address.getAddressID());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditAddressSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addrPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTF;
    private javax.swing.JLabel editAddrDescrLabel;
    private javax.swing.JLabel line1Label;
    private javax.swing.JTextField line1TF;
    private javax.swing.JLabel line2Label;
    private javax.swing.JTextField line2TF;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox primaryChkBx;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTF;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTF;
    // End of variables declaration//GEN-END:variables
}
