
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * This class provides a command line interface menu for a user to interact with 
 * the system as an employee.
 * @author Alexander
 */
public class EmployeeMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeMenuGUI.class.getName());
    private OrderManager gom;
    private DeliveryPersonManager dpm;
    private DeliveryPerson deliveryPerson;
    private int employeeId;
    private Restaurant restaurant;
    private Inventory inventory;
    private Menu menu;
    private CostCalculation cc;
    private RecipeManager rm;
    private DefaultListModel availableOrdersModel;
    private Map<Integer, Order> availableOrders;
    private DefaultListModel unfulfilledOrdersModel;
    private Map<Integer, Order> unfulfilledOrders;

    /**
     * Creates new form EmployeeMenuGUI
     */
    public EmployeeMenuGUI() {
        initComponents();
    }
    
    public EmployeeMenuGUI(DeliveryPersonManager dpm, int id, OrderManager gom, Menu menu,
            Restaurant restaurant, Inventory inventory, CostCalculation cc, RecipeManager rm){
        this();
        this.dpm = dpm;
        employeeId = id;
        deliveryPerson = dpm.searchDeliveryPerson(employeeId);
        this.gom = gom;
        this.restaurant = restaurant;
        this.menu = menu;
        this.inventory = inventory;
        this.cc = cc;
        this.rm = rm;
        
        viewAvailOrderInfoBttn.setEnabled(false);
        viewUnfllOrderInfoBttn.setEnabled(false);
        takeOnOrderBttn.setEnabled(false);
        fulfillOrderBttn.setEnabled(false);
        
        refreshInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordersPanel = new javax.swing.JPanel();
        takeOnOrderBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableOrdersLst = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        unfulfillOrdersLst = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewUnfllOrderInfoBttn = new javax.swing.JButton();
        viewAvailOrderInfoBttn = new javax.swing.JButton();
        fulfillOrderBttn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        systemSettingsBttn = new javax.swing.JButton();
        employeeMenuMenuBar = new javax.swing.JMenuBar();
        employeeSubmenu = new javax.swing.JMenu();
        profileMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        ordersSubmenu = new javax.swing.JMenu();
        orderHistMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        ordersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Orders"));

        takeOnOrderBttn.setText("Take On Selected Order");
        takeOnOrderBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeOnOrderBttnActionPerformed(evt);
            }
        });

        availableOrdersLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                availableOrdersLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(availableOrdersLst);

        unfulfillOrdersLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                unfulfillOrdersLstValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(unfulfillOrdersLst);

        jLabel3.setText("Available orders for Delivery: ");

        jLabel4.setText("Your unfulfilled orders:");

        viewUnfllOrderInfoBttn.setText("View Order info");
        viewUnfllOrderInfoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUnfllOrderInfoBttnActionPerformed(evt);
            }
        });

        viewAvailOrderInfoBttn.setText("View Order info");
        viewAvailOrderInfoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailOrderInfoBttnActionPerformed(evt);
            }
        });

        fulfillOrderBttn.setText("Fulfill Selected Order");
        fulfillOrderBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulfillOrderBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersPanelLayout.createSequentialGroup()
                        .addComponent(viewUnfllOrderInfoBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fulfillOrderBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ordersPanelLayout.createSequentialGroup()
                        .addComponent(viewAvailOrderInfoBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takeOnOrderBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(takeOnOrderBttn)
                    .addComponent(viewAvailOrderInfoBttn))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fulfillOrderBttn)
                    .addComponent(viewUnfllOrderInfoBttn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        welcomeLabel.setText("Welcome, Employee!");

        jLabel2.setText("What would you like to do today?");

        systemSettingsBttn.setText(" Go to System Settings");
        systemSettingsBttn.setToolTipText("");
        systemSettingsBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemSettingsBttnActionPerformed(evt);
            }
        });

        employeeSubmenu.setText("Employee");

        profileMenuItem.setText("Profile Settings");
        profileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuItemActionPerformed(evt);
            }
        });
        employeeSubmenu.add(profileMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        employeeSubmenu.add(logoutMenuItem);

        employeeMenuMenuBar.add(employeeSubmenu);

        ordersSubmenu.setText("Orders");

        orderHistMenuItem.setText("Order History");
        orderHistMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistMenuItemActionPerformed(evt);
            }
        });
        ordersSubmenu.add(orderHistMenuItem);

        employeeMenuMenuBar.add(ordersSubmenu);

        setJMenuBar(employeeMenuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(jLabel2)
                            .addComponent(systemSettingsBttn))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ordersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemSettingsBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void systemSettingsBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemSettingsBttnActionPerformed
        // TODO add your handling code here:
        new SystemSettingsSubmenuGUI(restaurant, menu, inventory, cc, rm).setVisible(true);
    }//GEN-LAST:event_systemSettingsBttnActionPerformed

    private void profileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuItemActionPerformed
        // TODO add your handling code here:
        new EmployeeSettingsSubmenuGUI(dpm, employeeId).setVisible(true);
    }//GEN-LAST:event_profileMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Log out", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            returnToLogIn();
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        refreshInfo();
        if(dpm.searchDeliveryPerson(employeeId) == null){
            returnToLogIn();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void availableOrdersLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_availableOrdersLstValueChanged
        // TODO add your handling code here:
        boolean itemSelected = availableOrdersLst.getSelectedIndex() > -1;
        viewAvailOrderInfoBttn.setEnabled(itemSelected);
        takeOnOrderBttn.setEnabled(itemSelected);
        
    }//GEN-LAST:event_availableOrdersLstValueChanged

    private void unfulfillOrdersLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_unfulfillOrdersLstValueChanged
        // TODO add your handling code here:
        boolean itemSelected = unfulfillOrdersLst.getSelectedIndex() > -1;
        viewUnfllOrderInfoBttn.setEnabled(itemSelected);
        fulfillOrderBttn.setEnabled(itemSelected);
    }//GEN-LAST:event_unfulfillOrdersLstValueChanged

    private void viewAvailOrderInfoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailOrderInfoBttnActionPerformed
        // TODO add your handling code here:
        String selectedOrder = availableOrdersLst.getSelectedValue();
        int id = retrieveOrderID(selectedOrder);
        Order order = availableOrders.get(id);
        new ViewOrderInfoGUI(order).setVisible(true);
    }//GEN-LAST:event_viewAvailOrderInfoBttnActionPerformed

    private void viewUnfllOrderInfoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUnfllOrderInfoBttnActionPerformed
        // TODO add your handling code here:
        String selectedOrder = unfulfillOrdersLst.getSelectedValue();
        int id = retrieveOrderID(selectedOrder);
        Order order = unfulfilledOrders.get(id);
        new ViewOrderInfoGUI(order).setVisible(true);
    }//GEN-LAST:event_viewUnfllOrderInfoBttnActionPerformed

    private void orderHistMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistMenuItemActionPerformed
        // TODO add your handling code here:
        new OrderHistoryGUI(deliveryPerson).setVisible(true);
    }//GEN-LAST:event_orderHistMenuItemActionPerformed

    private void takeOnOrderBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeOnOrderBttnActionPerformed
        // TODO add your handling code here:
        
        String selectedOrder = availableOrdersLst.getSelectedValue();
        String message = "<html>Are you sure you want to take on " + selectedOrder + "?" +
                         "<br>(If you have not done so already, please check the order information" +
                         "<br>before taking on the order.)";
        
        int result = JOptionPane.showConfirmDialog(this, message , "Take on Order", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            int id = retrieveOrderID(selectedOrder);
            assignOrder(id);
            
            String confirmMessage = "You have been assigned " + selectedOrder;
            
            JOptionPane.showMessageDialog(this, confirmMessage);
            
            refreshInfo();
        }
    }//GEN-LAST:event_takeOnOrderBttnActionPerformed

    private void fulfillOrderBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulfillOrderBttnActionPerformed
        // TODO add your handling code here:
        String selectedOrder = unfulfillOrdersLst.getSelectedValue();
        String message = "<html>Are you sure you have fulfilled " + selectedOrder + "?" +
                         "<br>(If you have not done so already, please check the order information" +
                         "<br>to ensure you are fulfilling the correct order.)";
        
        int result = JOptionPane.showConfirmDialog(this, message , "Fulfill Order", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            int id = retrieveOrderID(selectedOrder);
            fulfillOrder(id);
            
            String confirmMessage = selectedOrder + "has been fulfilled!";
            
            JOptionPane.showMessageDialog(this, confirmMessage);
            refreshInfo();
        }
    }//GEN-LAST:event_fulfillOrderBttnActionPerformed

    private void refreshInfo(){
        welcomeLabel.setText("Welcome, " + deliveryPerson.getName() + "!");
        showUnfulfilledOrders();
        showAvailableOrders();
    }
    
    @SuppressWarnings("unchecked")
    private void showUnfulfilledOrders(){
        unfulfilledOrders = deliveryPerson.getOrderHistory().getUnfulfilledOrders();
        
        
        unfulfilledOrdersModel = new DefaultListModel();
        
        if(!unfulfilledOrders.isEmpty()){
            for(int id: unfulfilledOrders.keySet()){
                Order order =  unfulfilledOrders.get(id);
                unfulfilledOrdersModel.addElement("Order #" + order.getOrderId());
            }
        }
        unfulfillOrdersLst.setModel(unfulfilledOrdersModel);
        unfulfillOrdersLst.updateUI();
    }
    
    @SuppressWarnings("unchecked")
    private void showAvailableOrders(){
        availableOrders = gom.getAvailableOrders();
        
        
        availableOrdersModel = new DefaultListModel();
        
        if(!availableOrders.isEmpty()){
            for(int id: availableOrders.keySet()){
                Order order =  availableOrders.get(id);
                availableOrdersModel.addElement("Order #" + order.getOrderId());
            }
        }
        availableOrdersLst.setModel(availableOrdersModel);
        availableOrdersLst.updateUI();
    }
    
    private int retrieveOrderID(String str){
        String orderIDStr = str.replace("Order #", "");
        int id = Integer.parseInt(orderIDStr);
        return id;
    }
    
    private void assignOrder(int id){
        Order order = gom.searchOrder(id);
        order.setDeliveryPerson(deliveryPerson);
        deliveryPerson.getOrderHistory().addOrder(order);
        new LoadSaveOrder().saveOrder(order);
    }
    
    private void fulfillOrder(int id){
        Order order = gom.searchOrder(id);
        order.setFulfillment(true);
        new LoadSaveOrder().saveOrder(order);
    }
    
    private void returnToLogIn(){
        this.dispose();
        new UserEntryMenuGUI(dpm, gom, menu, restaurant, inventory, cc, rm).setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> availableOrdersLst;
    private javax.swing.JMenuBar employeeMenuMenuBar;
    private javax.swing.JMenu employeeSubmenu;
    private javax.swing.JButton fulfillOrderBttn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem orderHistMenuItem;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JMenu ordersSubmenu;
    private javax.swing.JMenuItem profileMenuItem;
    private javax.swing.JButton systemSettingsBttn;
    private javax.swing.JButton takeOnOrderBttn;
    private javax.swing.JList<String> unfulfillOrdersLst;
    private javax.swing.JButton viewAvailOrderInfoBttn;
    private javax.swing.JButton viewUnfllOrderInfoBttn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
