
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class EmployeeSettingsSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerSettingsSubmenuGUI.class.getName());
 
    private DeliveryPersonManager dpm;
    private DeliveryPerson deliveryPerson;
    private int employeeId;
    
    /**
     * Creates new form CustomerSettingsSubmenuGUI
     */
    public EmployeeSettingsSubmenuGUI() {
        initComponents();
    }
    
    public EmployeeSettingsSubmenuGUI(DeliveryPersonManager dpm, int id){
        this();
        this.dpm = dpm;
        employeeId = id;
        deliveryPerson = dpm.searchDeliveryPerson(id);
        refreshInformation();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInfoPanel = new javax.swing.JPanel();
        employeeInfoLabel = new javax.swing.JLabel();
        editInfoButton = new javax.swing.JButton();
        settingsDescrLabel = new javax.swing.JLabel();
        contactInfoPanel = new javax.swing.JPanel();
        phoneNumberPanel = new javax.swing.JPanel();
        managePhoneButton = new javax.swing.JButton();
        vehicleInfoPanel = new javax.swing.JPanel();
        vehicleLabel = new javax.swing.JLabel();
        manageVehicletButton = new javax.swing.JButton();
        exitSaveButton = new javax.swing.JButton();
        exitWOSaveButton = new javax.swing.JButton();
        revertButton = new javax.swing.JButton();
        deleteAcctDescrLabel = new javax.swing.JLabel();
        deleteAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Profile Settings");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        customerInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Information"));
        customerInfoPanel.setToolTipText("Employee Information");

        employeeInfoLabel.setText("<html>Employee name: name<br>Employee ID: 000<br>Email Address: emailaddress12345@email.com<br>");

        editInfoButton.setText("Edit Information");
        editInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerInfoPanelLayout = new javax.swing.GroupLayout(customerInfoPanel);
        customerInfoPanel.setLayout(customerInfoPanelLayout);
        customerInfoPanelLayout.setHorizontalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editInfoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerInfoPanelLayout.setVerticalGroup(
            customerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoPanelLayout.createSequentialGroup()
                .addComponent(employeeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editInfoButton)
                .addContainerGap())
        );

        settingsDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        settingsDescrLabel.setText("Profile Settings");

        contactInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Information"));

        phoneNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Numbers"));

        managePhoneButton.setText("Manage Phone Numbers");
        managePhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePhoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout phoneNumberPanelLayout = new javax.swing.GroupLayout(phoneNumberPanel);
        phoneNumberPanel.setLayout(phoneNumberPanelLayout);
        phoneNumberPanelLayout.setHorizontalGroup(
            phoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managePhoneButton)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        phoneNumberPanelLayout.setVerticalGroup(
            phoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(managePhoneButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout contactInfoPanelLayout = new javax.swing.GroupLayout(contactInfoPanel);
        contactInfoPanel.setLayout(contactInfoPanelLayout);
        contactInfoPanelLayout.setHorizontalGroup(
            contactInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phoneNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contactInfoPanelLayout.setVerticalGroup(
            contactInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactInfoPanelLayout.createSequentialGroup()
                .addComponent(phoneNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        vehicleInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delivery Vehicle Information"));

        vehicleLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        vehicleLabel.setText("<html>Vehicle: 0000 Make Model<br>Color: color<br>Body Style: body style<br>License plate: AAA000");

        manageVehicletButton.setText("Manage Vehicle Information");
        manageVehicletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVehicletButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleInfoPanelLayout = new javax.swing.GroupLayout(vehicleInfoPanel);
        vehicleInfoPanel.setLayout(vehicleInfoPanelLayout);
        vehicleInfoPanelLayout.setHorizontalGroup(
            vehicleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageVehicletButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehicleInfoPanelLayout.setVerticalGroup(
            vehicleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageVehicletButton)
                .addContainerGap())
        );

        exitSaveButton.setText("Exit and Save");
        exitSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSaveButtonActionPerformed(evt);
            }
        });

        exitWOSaveButton.setText("Exit Without Saving");
        exitWOSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitWOSaveButtonActionPerformed(evt);
            }
        });

        revertButton.setText("Revert Information");
        revertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revertButtonActionPerformed(evt);
            }
        });

        deleteAcctDescrLabel.setText("If you want to delete your account,");

        deleteAccountLabel.setForeground(new java.awt.Color(255, 0, 0));
        deleteAccountLabel.setText("click here");
        deleteAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAccountLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsDescrLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(deleteAcctDescrLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteAccountLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(exitSaveButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exitWOSaveButton)))
                                .addGap(10, 10, 10)
                                .addComponent(revertButton)))
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitSaveButton)
                    .addComponent(exitWOSaveButton)
                    .addComponent(revertButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAcctDescrLabel)
                    .addComponent(deleteAccountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButtonActionPerformed
        // TODO add your handling code here:
        UserInfoGUI uiGUI = new UserInfoGUI(deliveryPerson);
        uiGUI.setVisible(true);
    }//GEN-LAST:event_editInfoButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        refreshInformation();
    }//GEN-LAST:event_formWindowGainedFocus

    private void managePhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePhoneButtonActionPerformed
        // TODO add your handling code here:
        PhoneSubmenuGUI psGUI = new PhoneSubmenuGUI(deliveryPerson);
        psGUI.setVisible(true);
    }//GEN-LAST:event_managePhoneButtonActionPerformed

    private void manageVehicletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVehicletButtonActionPerformed
        // TODO add your handling code here:
        new EditVehicleSubmenuGUI(deliveryPerson.getDeliveryVehicle()).setVisible(true);
    }//GEN-LAST:event_manageVehicletButtonActionPerformed

    private void exitSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSaveButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit and save?", "Exit and Save", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            new LoadSaveDeliveryPerson().saveDeliveryPerson(deliveryPerson);
            this.dispose();
        }
    }//GEN-LAST:event_exitSaveButtonActionPerformed

    private void exitWOSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitWOSaveButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit without saving?", "Exit Without Saving", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            revertInformation();
            this.dispose();
        }
    }//GEN-LAST:event_exitWOSaveButtonActionPerformed

    private void revertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revertButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to revert your changes?", "Revert Changes", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            revertInformation();
        }
    }//GEN-LAST:event_revertButtonActionPerformed

    private void deleteAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAccountLabelMouseClicked
        // TODO add your handling code here:
        String message = "<html>Are you sure you want to delete your profile?<br>"+
                         "WARNING!!! Once you delete your profile, you can't get it back.";
        int result = JOptionPane.showConfirmDialog(this, message, "Delete Profile", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            resetDeliveryPerson(deliveryPerson.getID());
            dpm.removeDeliveryPerson(deliveryPerson.getID());
            this.dispose();
        }       
    }//GEN-LAST:event_deleteAccountLabelMouseClicked
    
    private void refreshInformation(){
        displayDeliveryPersonInfo();
        displayVehicle();
    }
    
    private void displayDeliveryPersonInfo(){
        employeeInfoLabel.setText(deliveryPerson.toString());
    }

    private void displayVehicle(){
        Vehicle vehicle = deliveryPerson.getDeliveryVehicle();
        if(vehicle != null){
            vehicleLabel.setText(vehicle.toString());
        }
        else{
            vehicleLabel.setText("Delivery Vehicle has not been set.");
        }
    }
    
    private void revertInformation(){
        DeliveryPerson original = new LoadSaveDeliveryPerson().loadDeliveryPerson(employeeId);
        
        deliveryPerson.setName(original.getName());
        deliveryPerson.setEmail(original.getEmail());
        deliveryPerson.setPassword(original.getPassword());
        deliveryPerson.setDeliveryVehicle(original.getDeliveryVehicle());
        deliveryPerson.setPNM(original.getPNM());
    }
    
    private void resetDeliveryPerson(int id){
        DeliveryPerson fauxDP = new DeliveryPerson("DeliveryPerson", id);
        fauxDP.setEmail(String.valueOf(id * id));
        fauxDP.setPassword("password");
        if(deliveryPerson.getDeliveryVehicle() != null)
            fauxDP.getDeliveryVehicle().equals(deliveryPerson.getDeliveryVehicle());
        
        new LoadSaveDeliveryPerson().saveDeliveryPerson(fauxDP);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerSettingsSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contactInfoPanel;
    private javax.swing.JPanel customerInfoPanel;
    private javax.swing.JLabel deleteAccountLabel;
    private javax.swing.JLabel deleteAcctDescrLabel;
    private javax.swing.JButton editInfoButton;
    private javax.swing.JLabel employeeInfoLabel;
    private javax.swing.JButton exitSaveButton;
    private javax.swing.JButton exitWOSaveButton;
    private javax.swing.JButton managePhoneButton;
    private javax.swing.JButton manageVehicletButton;
    private javax.swing.JPanel phoneNumberPanel;
    private javax.swing.JButton revertButton;
    private javax.swing.JLabel settingsDescrLabel;
    private javax.swing.JPanel vehicleInfoPanel;
    private javax.swing.JLabel vehicleLabel;
    // End of variables declaration//GEN-END:variables
}
