/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * This class provides a main menu GUI to the user. It is used to give the user
 * the option to enter either as a customer or an employee.
 * @author Alexander
 */
public class MainMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuGUI.class.getName());
    /**
     * The customer manager to be used throughout the entire system.
     */
    private CustomerManager cm;
    /**
     * The delivery person manager to be used throughout the entire system.
     */
    private DeliveryPersonManager dpm;
    /**
     * A UserEntryMenuGUI object to be used to allow customer users to enter the
     * system.
     */
    private UserEntryMenuGUI customerEntry;
    /**
     * A UserEntryMenuGUI object to be used to allow employee users to enter the
     * system.
     */
    private UserEntryMenuGUI employeeEntry;
    
    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
    }
    
    /**
     * Creates a new form MainMenuGUI by calling the no argument constructor. 
     * It also initializes the customer manager, delivery person manager,
     * general order manager, main menu, restaurant, inventory, and cost
     * calculation objects to their respective arguments.
     * 
     * @param cm    The customer manager being used throughout the system.
     * @param dpm   The delivery person manager being used throughout the system.
     * @param gom   The general order manager that stores and manages all of the
     *              orders within the system.
     * @param menu  The food menu to be used throughout the entire program.
     * @param restaurant    The restaurant that sells the food in the system.
     * @param inventory     The inventory of ingredients for each dish
     * @param cc    The cost calculation object to calculate the cost of orders.
     * @param rm    The recipe manager being used throughout the system.
     */
    public MainMenuGUI(CustomerManager cm, DeliveryPersonManager dpm, OrderManager gom, 
            Menu menu, Restaurant restaurant, Inventory inventory, CostCalculation cc,
            RecipeManager rm){
        this();
        this.cm = cm;
        this.dpm = dpm;
        customerEntry = new UserEntryMenuGUI(this.cm, gom, menu, restaurant, inventory, cc);
        employeeEntry = new UserEntryMenuGUI(this.dpm, gom, menu, restaurant, inventory, cc, rm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        entryBtnPanel = new javax.swing.JPanel();
        btnCustEntry = new javax.swing.JButton();
        btnEmpEntry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        welcomeLabel.setText("Welcome To the Food Delivery \nManagement System!");

        entryBtnPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCustEntry.setText("Enter as Customer");
        btnCustEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustEntryActionPerformed(evt);
            }
        });

        btnEmpEntry.setText("Enter as Employee");
        btnEmpEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entryBtnPanelLayout = new javax.swing.GroupLayout(entryBtnPanel);
        entryBtnPanel.setLayout(entryBtnPanelLayout);
        entryBtnPanelLayout.setHorizontalGroup(
            entryBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryBtnPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(entryBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustEntry)
                    .addComponent(btnEmpEntry))
                .addGap(36, 36, 36))
        );
        entryBtnPanelLayout.setVerticalGroup(
            entryBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryBtnPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnCustEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpEntry)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(welcomeLabel)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entryBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(entryBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method displays the Customer Entry menu to the user.
     * 
     * @param evt   The event that occurs when the customer entry button is
     *              clicked.
     */
    private void btnCustEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustEntryActionPerformed
        // TODO add your handling code here:
        customerEntry.setVisible(true);
    }//GEN-LAST:event_btnCustEntryActionPerformed

    /**
     * This method displays the Employee Entry menu to the user.
     * 
     * @param evt   The event that occurs when the employee entry button is
     *              clicked.
     */
    private void btnEmpEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpEntryActionPerformed
        employeeEntry.setVisible(true);
    }//GEN-LAST:event_btnEmpEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustEntry;
    private javax.swing.JButton btnEmpEntry;
    private javax.swing.JPanel entryBtnPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
