
import java.util.Map;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * This class provides a GUI for the user to view their order history.
 * @author Alexander
 */
public class OrderHistoryGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddressesSubmenuGUI.class.getName());
    /**
     * The person whose order history is being displayed.
     */
    
    private OrderManager om;
    
    /**
     * A DefaultListModel to be used to store all of the orders in the orderList
     * on the GUI form.
     */
    private DefaultListModel orderModel;
    
    /**
     * Creates new form AddressesSubmenuGUI. It also initializes the orderModel
     * to a new DefaultListModel() object. It also disables the 
     * viewOrderInfoBttn since no order will be selected when the form is first
     * created.
     */
    public OrderHistoryGUI() {
        orderModel = new DefaultListModel();
        initComponents();
        viewOrderInfoBttn.setEnabled(false);
    }
    /**
     * Creates new form AddressesSubmenuGUI by calling the no argument
     * constructor. It also sets the om variable to the order manager associated
     * with the input person parameter. It then calls the initializeOrders()
     * method to initialize the orderModel to store all of the orders associated
     * with the person. Finally, the orderHistoryDescrLabel's text is modified
     * to show the person's name.
     * 
     * @param person The person whose order history is being displayed.
     */
    public OrderHistoryGUI(Person person) {
        this();
        om = person.getOrderHistory();
        initializeOrders();
        orderHistoryDescrLabel.setText("Order History for " + person.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderHistoryDescrLabel = new javax.swing.JLabel();
        orderHistoryPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        viewOrderInfoBttn = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        orderHistoryDescrLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        orderHistoryDescrLabel.setText("Order History for Person");

        orderHistoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Order History"));

        orderList.setModel(orderModel);
        orderList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                orderListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(orderList);

        viewOrderInfoBttn.setText("View Order Information");
        viewOrderInfoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderInfoBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderHistoryPanelLayout = new javax.swing.GroupLayout(orderHistoryPanel);
        orderHistoryPanel.setLayout(orderHistoryPanelLayout);
        orderHistoryPanelLayout.setHorizontalGroup(
            orderHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderHistoryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewOrderInfoBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderHistoryPanelLayout.setVerticalGroup(
            orderHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderHistoryPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewOrderInfoBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderHistoryDescrLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(orderHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderHistoryDescrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderHistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This method closes the form then the OK button is used.
     * 
     * @param evt The event that occurs when the OK button is used.
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * This method is called any time the selected item in the order list is 
     * changed. It enables the viewOrderInfoBttn whenever an order is selected
     * in the list.
     * 
     * @param evt The event that occurs when the viewOrderInfoBttn is used.
     */
    private void orderListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_orderListValueChanged
        // TODO add your handling code here:
        viewOrderInfoBttn.setEnabled(orderList.getSelectedIndex() > -1);
    }//GEN-LAST:event_orderListValueChanged

    /**
     * This method refreshes the orders list any time the window gains focus.
     * This is done by calling the initializeOrders() method again to reset the
     * ordersList.
     * 
     * @param evt The event that occurs when the window gains focus.
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        initializeOrders();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * This method displays the information about the order selected in the 
     * orderList. It retrieves the id of the currently selected order and
     * searches for that order within the order manager. It then passes the 
     * returned order object as the argument for the ViewOrderInfoGUI.
     * 
     * @param evt The event that occurs when the viewOrderInfoBttn is used.
     */
    private void viewOrderInfoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderInfoBttnActionPerformed
        // TODO add your handling code here:
        String selectedOrder = orderList.getSelectedValue();
        int id = retrieveOrderID(selectedOrder);
        
        Order order = om.searchOrder(id);
        
        new ViewOrderInfoGUI(order).setVisible(true);
    }//GEN-LAST:event_viewOrderInfoBttnActionPerformed
    
    /**
     * This method initializes the orderModel so the orderList on the GUI
     * contains all of the orders within the person's order history. Each order
     * within the order manager is added to the order model, simply displaying
     * the order number. Once all orders have been added to the orderModel, it
     * is set as the model for the orderList, and the updateUI() method for the
     * orderList is called to update any changes.
     */
    private void initializeOrders(){
        Map<Integer, Order> orders = om.getAllOrders();
        
        for(int id: orders.keySet()){
            Order order = om.searchOrder(id);
            orderModel.addElement("Order #" + order.getOrderId());
        }
        
        orderList.setModel(orderModel);
        orderList.updateUI();
    }
    
    /**
     * This method returns the order ID for the selected order in the orderList.
     * the "Order #" sub string of the str parameter is removed to obtain just 
     * the order number. This string value of the order ID is then parsed
     * as an integer, and the value of that integer is returned.
     * 
     * @param str The string value of the order that is stored in the orderList.
     * @return The parsed string ID as an integer.
     */
    private int retrieveOrderID(String str){
        String orderIDStr = str.replace("Order #", "");
        int id = Integer.parseInt(orderIDStr);
        return id;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddressesSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel orderHistoryDescrLabel;
    private javax.swing.JPanel orderHistoryPanel;
    private javax.swing.JList<String> orderList;
    private javax.swing.JButton viewOrderInfoBttn;
    // End of variables declaration//GEN-END:variables
}
