/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class SystemSettingsSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SystemSettingsSubmenuGUI.class.getName());

    /**
     * Creates new form SystemSettingsSubmenuGUI
     */
    public SystemSettingsSubmenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemSettingsLabel = new javax.swing.JLabel();
        exitBttn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mngRestaurantBttn = new javax.swing.JButton();
        mngMenuBttn = new javax.swing.JButton();
        mngInventoryBttn = new javax.swing.JButton();
        mngCostBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        systemSettingsLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        systemSettingsLabel.setText("System Settings");

        exitBttn.setText("Exit");
        exitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mngRestaurantBttn.setText("Manage Restaurant Information");
        mngRestaurantBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngRestaurantBttnActionPerformed(evt);
            }
        });

        mngMenuBttn.setText("Manage Menu");
        mngMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngMenuBttnActionPerformed(evt);
            }
        });

        mngInventoryBttn.setText("Manage Inventory");
        mngInventoryBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngInventoryBttnActionPerformed(evt);
            }
        });

        mngCostBttn.setText("Manage Cost Settings");
        mngCostBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCostBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngRestaurantBttn)
                    .addComponent(mngMenuBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mngInventoryBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mngCostBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mngRestaurantBttn)
                .addGap(18, 18, 18)
                .addComponent(mngMenuBttn)
                .addGap(18, 18, 18)
                .addComponent(mngInventoryBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(mngCostBttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemSettingsLabel)
                    .addComponent(exitBttn))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBttn)
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(416, 258));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mngRestaurantBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngRestaurantBttnActionPerformed
        // TODO add your handling code here:
        new RestaurantManagementMenuGUI().setVisible(true);
    }//GEN-LAST:event_mngRestaurantBttnActionPerformed

    private void mngMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngMenuBttnActionPerformed
        // TODO add your handling code here:
        new MenuManagementMenuGUI().setVisible(true);
    }//GEN-LAST:event_mngMenuBttnActionPerformed

    private void mngInventoryBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngInventoryBttnActionPerformed
        // TODO add your handling code here:
        new InventoryManagementMenuGUI().setVisible(true);
    }//GEN-LAST:event_mngInventoryBttnActionPerformed

    private void mngCostBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCostBttnActionPerformed
        // TODO add your handling code here:
        new CostCalculationMenuGUI().setVisible(true);
    }//GEN-LAST:event_mngCostBttnActionPerformed

    private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SystemSettingsSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mngCostBttn;
    private javax.swing.JButton mngInventoryBttn;
    private javax.swing.JButton mngMenuBttn;
    private javax.swing.JButton mngRestaurantBttn;
    private javax.swing.JLabel systemSettingsLabel;
    // End of variables declaration//GEN-END:variables
}
