
/**
 * This class provides a GUI menu for an employee user to manage the system 
 * settings
 *
 * @author Alexander
 */
public class SystemSettingsSubmenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SystemSettingsSubmenuGUI.class.getName());
    
    /**
     * The restaurant that sells the food in the system.
     */
    private Restaurant restaurant;
    
    /**
     * The food menu that has all of the food items.
     */
    private Menu menu;
    
    /**
     * The inventory of ingredients for each dish.
     */
    private Inventory inventory;
    
    /**
     * The cost calculation object to be used to calculate the cost of orders
     * and keep a standard tax rate.
     */
    private CostCalculation cc;
    
    /**
     * Creates new form SystemSettingsSubmenuGUI.
     */
    public SystemSettingsSubmenuGUI() {
        initComponents();
    }
    
    /**
     * Creates new form SystemSettingsSubmenuGUI by calling the no argument
     * constructor. It also initializes the instance variables based on their
     * respective input parameters.
     * @param restaurant      The restaurant that sells the food in the system.
     * @param menu            The food menu to be used throughout the entire 
     *                        program.
     * @param inventory       The inventory of ingredients for each dish
     * @param cc              The cost calculation object to calculate the cost 
     *                        of orders and keep a standard tax rate throughout
     *                        the system. 
     */
    public SystemSettingsSubmenuGUI(Restaurant restaurant, Menu menu, Inventory inventory,
            CostCalculation cc) {
        this();
        this.restaurant = restaurant;
        this.menu = menu;
        this.inventory = inventory;
        this.cc = cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemSettingsLabel = new javax.swing.JLabel();
        exitBttn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mngRestaurantBttn = new javax.swing.JButton();
        mngMenuBttn = new javax.swing.JButton();
        mngInventoryBttn = new javax.swing.JButton();
        mngCostBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        systemSettingsLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        systemSettingsLabel.setText("System Settings");

        exitBttn.setText("Exit");
        exitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mngRestaurantBttn.setText("Manage Restaurant Information");
        mngRestaurantBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngRestaurantBttnActionPerformed(evt);
            }
        });

        mngMenuBttn.setText("Manage Menu");
        mngMenuBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngMenuBttnActionPerformed(evt);
            }
        });

        mngInventoryBttn.setText("Manage Inventory");
        mngInventoryBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngInventoryBttnActionPerformed(evt);
            }
        });

        mngCostBttn.setText("Manage Cost Settings");
        mngCostBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngCostBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngRestaurantBttn)
                    .addComponent(mngMenuBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mngInventoryBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mngCostBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mngRestaurantBttn)
                .addGap(18, 18, 18)
                .addComponent(mngMenuBttn)
                .addGap(18, 18, 18)
                .addComponent(mngInventoryBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(mngCostBttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemSettingsLabel)
                    .addComponent(exitBttn))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBttn)
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(416, 258));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method opens the restaurant management menu GUI when the 
     * mngRestaurantBttn is used.
     * 
     * @param evt The event that occurs when the mngRestaurantBttn is used.
     */
    private void mngRestaurantBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngRestaurantBttnActionPerformed
        new RestaurantManagementMenuGUI(restaurant).setVisible(true);
    }//GEN-LAST:event_mngRestaurantBttnActionPerformed

    /**
     * This method opens the Menu Management MenuGUI when the mngMenuBttn is
     * used.
     * 
     * @param evt The event that occurs when the mngMenuBttn is used.
     */
    private void mngMenuBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngMenuBttnActionPerformed
        // TODO add your handling code here:
        new MenuManagementMenuGUI(menu, ).setVisible(true);
    }//GEN-LAST:event_mngMenuBttnActionPerformed

    /**
     * This method opens the Inventory Management Menu GUI when the 
     * mngInventoryBttn is used.
     * 
     * @param evt The event that occurs when the mngInventoryBttn is used.
     */
    private void mngInventoryBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngInventoryBttnActionPerformed
        // TODO add your handling code here:
        new InventoryManagementMenuGUI(inventory).setVisible(true);
    }//GEN-LAST:event_mngInventoryBttnActionPerformed

    /**
     * This method opens the Cost Calculation Menu GUI when the mngCostBttn is 
     * used.
     * 
     * @param evt The event that occurs when the mngCostBttn is used.
     */
    private void mngCostBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngCostBttnActionPerformed
        // TODO add your handling code here:
        new CostCalculationMenuGUI(cc).setVisible(true);
    }//GEN-LAST:event_mngCostBttnActionPerformed

    /**
     * This method closes the window then the exitBttn is used
     * 
     * @param evt The event that occurs when the exitBttn is used.
     */
    private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SystemSettingsSubmenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mngCostBttn;
    private javax.swing.JButton mngInventoryBttn;
    private javax.swing.JButton mngMenuBttn;
    private javax.swing.JButton mngRestaurantBttn;
    private javax.swing.JLabel systemSettingsLabel;
    // End of variables declaration//GEN-END:variables
}
